### PR TITLE
Use __DIR__ instead of getcwd()

### PR DESCRIPTION
**Pull request by travisaustin**
getcwd() returns the directory in which the user last changed to,
irrelevant of where ladder.php is located. In other words, if you do
“cd /root/test/“ followed by “php /vendor/lib/ladder/ladder.php”,
getcwd() will return /root/test.

Using the **DIR** constant, on the other hand, always uses the
directory location of the file containing the **DIR** constant. In
other words, no matter how you launch ladder.php, it will always return
the correct directory.

### CODE REVIEW

**Comment by Drarok** [comment]
Hmm, I vaguely remember this now. The problem is that ladder needs to know some information about your application. You can't place your migration files in `vendor/lib/ladder/migrations` (well, you _can_, but you shouldn't put anything in vendor that's not actually a vendor library). So by default, Ladder expects you to create a `ladder` directory at the root of your project for database configuration files, migration files, etc.

_I think._

Edit: If there's a better way to find the root of the application (without just looping up through `../` looking for `composer.json`), I'd be happy to include it. Your changes for timestamp fields don't really make sense as part of this PR, however.

**Comment by travisaustin** [comment]
That makes sense. I would assume that config files should be the same way? They should live in a folder in the root directory?

Also, there are a few commits in my pull request. What do you think of the others?

---

Travis Austin
Rezitech, Inc.
625 S Palm Street
La Habra, CA 90631

Direct + SMS: 714-784-0334
Main: 877-407-2000
Fax: 866-881-0148
Web: www.rezitech.comhttp://www.rezitech.com/

On Oct 1, 2014, at 2:36 AM, Mat Gadd <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmm, I vaguely remember this now. The problem is that ladder needs to know some information about your application. You can't place your migration files in vendor/lib/ladder/migrations (well, you can, but you shouldn't put anything in vendor that's not actually a vendor library). So by default, Ladder expects you to create a ladder directory at the root of your project for database configuration files, migration files, etc.

I think.

**Comment by Drarok** [comment]
Yeah, I everything that Ladder is interested in should be in `$application_path`; Migrations, config, etc.

As for the other commits, I'll have a proper look now, but I'd need them as a separate PR to merge them. :)

**Comment by travisaustin** [comment]
I'm closing this in favor of #4 and #5.

**Pull request closed without merging**
